version: "3"
services:
  react-app:
    image: quanghoang0403/react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    image: quanghoang0403/api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
